# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilometro',
            name='entrada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kilometro',
            name='fechafin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kilometro',
            name='fechaini',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kilometro',
            name='kmfin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kilometro',
            name='kmini',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kilometro',
            name='tipo',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='descripcion',
            field=models.CharField(default='pordefault', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parametro',
            name='valido',
            field=models.CharField(default='T', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
