# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viaje', '0002_auto_20200512_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
