# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-24 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viaje', '0003_auto_20200512_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilometro',
            name='usuario',
            field=models.CharField(default='testman', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kilometro',
            name='vehiculo',
            field=models.CharField(default='micocheaxul', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametro',
            name='usuario',
            field=models.CharField(default='testman', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kilometro',
            name='tipo',
            field=models.CharField(choices=[(b'1', b'Didi'), (b'2', b'Uber'), (b'3', b'Cabify'), (b'99', b'Familiar')], default=99, max_length=1),
        ),
    ]
