# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-27 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viaje', '0004_auto_20200524_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilometro',
            name='parametro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_viaje.Parametro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kilometro',
            name='tipo',
            field=models.CharField(choices=[(b'1', b'Didi'), (b'2', b'Uber'), (b'3', b'Cabify'), (b'99', b'Familiar')], default=b'99', max_length=2),
        ),
    ]
