# Generated by Django 3.0.6 on 2020-06-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viaje', '0006_auto_20200603_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aldia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtAldia', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('usuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtNomAlim', models.CharField(max_length=100)),
                ('txtDescrip', models.CharField(max_length=100)),
                ('intKCal', models.IntegerField()),
                ('usuario', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('fuente', models.CharField(max_length=200)),
                ('cantpor', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateTimeField()),
                ('usuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Porcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtMedida', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('usuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtDescripcion', models.CharField(max_length=100)),
                ('txtColor', models.CharField(max_length=45)),
                ('fecha', models.DateField()),
                ('usuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('usuario', models.CharField(max_length=45)),
                ('porciones', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aldia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_viaje.Aldia')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_viaje.Alimento')),
            ],
        ),
        migrations.AddField(
            model_name='alimento',
            name='porcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_viaje.Porcion'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_viaje.Tipo'),
        ),
    ]
