# Generated by Django 3.0.6 on 2020-07-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viaje', '0007_auto_20200625_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSRegis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('cel', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField()),
                ('usuario', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alimento',
            options={'ordering': ['txtNomAlim']},
        ),
    ]
