# Generated by Django 3.0.6 on 2020-07-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viaje', '0008_auto_20200706_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porcion',
            options={'ordering': ['txtMedida']},
        ),
    ]
